### ISSUE TITLE
Not able to Compile my Xcode Project on xcode 10 Swift 4.2 

### ISSUE THREAD

**Issue by habiburrahuman** [socketio/socket.io-client-swift#1092]
<img width="1440" alt="screen shot 2018-09-18 at 7 22 25 pm" src="https://user-images.githubusercontent.com/13046503/45692370-371e4380-bb78-11e8-8ab3-9f77daa8cab1.png">

Not able to Compile my Xcode Project on New xcode 10 Swift 4.2 please fix and release new pod version

**Comment by nuclearace** [comment]
@habiburrahuman Did you do a clean pod install? Usually this error happens if you change xcode versions and don't do a complete clean install.

**Comment by nuclearace** [comment]
I verified that it still compiles in 4.2, so it must be some CocoaPods thing.

**Comment by habiburrahuman** [comment]
Thanks dude

**Comment by Yelles** [comment]
unable to compile with Xcode 10 for me too, using **carthage** i get : 

`Failed to write to /Users/me/Develop/imagyn-ios/Carthage/Build/iOS/SocketIO.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “SocketIO.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/me/Library/Developer/Xcode/DerivedData/Socket.IO-Client-Swift-ddaavvadtbjffvamcqqjjejfmohc/Build/Products/Release-iphoneos/SocketIO.framework, NSUnderlyingError=0x7f9f19e27b90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`
