### ISSUE TITLE
Socket is disconnected in background while go in foreground show socket status "connected." 

### ISSUE THREAD

**Issue by VishveshLad** [socketio/socket.io-client-swift#1151]
I face one issue that my app in the background then open app go in foreground mode I called one emit socket call but I can't receive any response from the server. I was checked, there was socket state show me connected at that time.
What is the solution for this issue? Please give me a response as soon as early. Thank you.

**Comment by nuclearace** [comment]
@VishveshLad Probably the best solution is to not rely on the socket for automatic reconnection/connection logic on iOS. Because the lib is platform agnostic (with linux support still a wanted goal in the future), the client doesn't make any special cases for iOS and its background execution model.

The general solution would be do add a background execution task to disconnect the socket, and then when the socket comes back into the foreground, reconnect it.
