### ISSUE TITLE
Using Socket.io with starscream 3.0.5

### ISSUE THREAD

**Issue by foward** [socketio/socket.io-client-swift#1315]
Hi !

One project is using another library that uses startscream 3.0.5 so we wanted to use socket.io but is conflicting since socket.io latest uses the latest starscrem 3.1.  Can we resolve this issue with an older version of Socket.io which uses starscream 3.0.5? Thanks!!!

**Comment by nuclearace** [comment]
see #1309

**Comment by foward** [comment]
@nuclearace sorry but I don't really understand the link of the comment Erik ... Could you please explain to us why we need to refer to that? Thanks!

**Comment by nuclearace** [comment]
@foward I'm currently working on a version that supports the newest Starscream version. Currently that PR only supports socket.io 3.0, but I'm going to go back and make it configurable for socket.io 2 and 3, since it shouldn't be too difficult.

**Comment by nuclearace** [comment]
But beyond that, I'm not sure of a solution to use new starscream in an older socket.io version.

**Comment by Abdullah-00** [comment]
Hi Erik,
Just to clarify the issue we have. We are using another library that depends on Starscream (3.0.5), so when we try to install Socket.IO, the installation fails because Socket.IO uses a more recent version of Starscream which is 3.1.

The question is, how can we install Socket.IO alongside the other library that we are using without having this Starscream version conflict?

Thanks.

**Comment by nuclearace** [comment]
@Abdullah-00 I'm not sure how to do that exactly, if it's even possible.

**Comment by foward** [comment]
Thanks Erik, Do you have some recommendations how to follow in this case? Much appreciated ! Regards
