### ISSUE TITLE
App crashed on iOS9 while reading utf8 data

### ISSUE THREAD

**Issue by gen1us2k** [socketio/socket.io-client-swift#308]
Hello. I have some problems while receiving cyrillic data on "chat message" event

```
    mutating func read(readLength: Int) -> String {
        let readString = message[currentIndex..<currentIndex.advancedBy(readLength)]
        advanceIndexBy(readLength)
        return readString
    }

fatal error: can not increment endIndex
at SocketStringReader struct
```
But english words works well
Test data:
Ы
Привет
Йопта

**Comment by nuclearace** [comment]
What server are you using? Because it seems to work fine with the node.js one.

**Comment by gen1us2k** [comment]
golang implementation

**Comment by gen1us2k** [comment]
But on device it not crashes, but failed to decode json

**Comment by gen1us2k** [comment]
And it works on android/browser clients

**Comment by nuclearace** [comment]
Okay then it's probably because the golang version doesn't double encode utf8 like the node version does, in which case you'll have to make a change to the client.

https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketFixUTF8.swift#L28 these methods should probably just immediatly return the string in your case

**Comment by nuclearace** [comment]
I'll try and add an option to toggle this

**Comment by nuclearace** [comment]
v5.4.0 has an option to toggle double encoding

**Comment by gen1us2k** [comment]
@nuclearace Thanks. I'll test and give you feedback

**Comment by gen1us2k** [comment]
@nuclearace It works. Thank you
