### ISSUE TITLE
how to remove a particular listener?

### ISSUE THREAD

**Issue by njawahire** [socketio/socket.io-client-swift#375]

**Comment by nuclearace** [comment]
If you only have one of a listener you can use

```swift
socket.off("event")
```

but if you want to be super specific you'll have to save the UUID that's returned from `on`

```swift
let uuid = socket.on("event", someHandler)
socket.off(id: uuid)
```

**Comment by njawahire** [comment]
thanks nuclearace it helped me......

**Comment by tomergev** [comment]
This answer did not work for me! Instead I did this (and it worked!): 
`socket.on("event" , someHandler)
/* Can use socket. off, removeListener, removeAllListeners, or removeEventListener because they all point to the same function source code: https://github.com/component/emitter/blob/092199bf0e329998a915d230a74bf9405365dab7/index.js#L86  */
socket.removeListener("event", someHandler)`

**Comment by aajinkya1203** [comment]
Thanks @tomergev 
it worked out well for me!
