### ISSUE TITLE
Socket.emit

### ISSUE THREAD

**Issue by alextheguitarman** [socketio/socket.io-client-swift#529]
Hello' i'm trying to send a string from my iPhone app to my arduino Mega Server.

let socket = SocketIOClient(socketURL: URL(string: "http://192.168.0.5:1124")!)
socket.connect()
socket.emit("Hello from iPhone")

but even if i see the iPhone hooked by server, no strings are transmitted ! 
i'm do NOT understanding something ... O_o

**Comment by nuclearace** [comment]
Is your server actually a socket.io server? Or is it a WebSocket server? If it's the latter. You need https://github.com/daltoniam/Starscream, which is a plain old WebSocket client. (Also used in this library)

If it is a socket.io server, make sure that your socket is properly scoped as a property, or global variable. Otherwise it'll be released immediately after going out of scope.
