### ISSUE TITLE
socket.io-client-swift Use in Objective-C Project

### ISSUE THREAD

**Issue by Mfk759853063** [socketio/socket.io-client-swift#686]
<img width="690" alt="default" src="https://cloud.githubusercontent.com/assets/4027519/26054749/5cd3f9f4-39a0-11e7-9171-17df064cefee.png">
How to get status Value in Objective-C?

**Comment by nuclearace** [comment]
I haven't tested, but I think status is an int in Objective-C, and you could probably compare it to however [SocketIOClientStatus](https://github.com/socketio/socket.io-client-swift/blob/master/Source/SocketIOClientStatus.swift) gets bridged. I encourage people to use Swift if possible, since that's what I intended this library to used from, and as such the Objective-C API is going to be suboptimal.
