### ISSUE TITLE
Should all SocketIOClient's emit calls be made in the handleQueue?

### ISSUE THREAD

**Issue by gupalov** [socketio/socket.io-client-swift#694]
Here is a quote from the Breaking Changes of  the v9.0.0 release:
"All interaction with the socket should be done through the queue that is passed to the socket."

Does this mean SocketIOClient's emit/connect/disconnect should be called in the **handleQueue**?
I am asking the question because I am wondering if the answer is "yes", why doesn't the SocketIOClient handle these cases internally executing the code in the  **handleQueue**?

**Comment by nuclearace** [comment]
The answer currently is yes. I'm going to add some helper methods that do the dispatching for methods so it's not a giant pyramid of indent, but any access to properties need to be on the handleQueue.

**Comment by nuclearace** [comment]
The more I dig into this, the weirder it becomes. Some of the methods run into strange behavior if the client tries dispatching, like `off`, and some it just can't, like the ones that return values.

So I'm starting to lean towards having the user explicitly dispatching, rather than introducing a bunch of trampoline methods and inconsistency.

**Comment by gupalov** [comment]
Thank you for your answer @nuclearace
