### ISSUE TITLE
Move Starscream dependency to own repo

### ISSUE THREAD

**Issue by nuclearace** [socketio/socket.io-client-swift#721]
That way it's easier to maintain and people don't think it's a direct issue with this library.

**Comment by hashier** [comment]
But now people (I) wonder what should I do if I had socket.io-client-swift and Starscream before in my project.

Should I now remove Starscream and just let the copied version be in there? Are there any differences between Starscream and StarscreamSocketIO? What if they diverge? Why not just stay with a normal dependency?

**Comment by nuclearace** [comment]
It's always had this issue, and it never was a "normal dependency." This project is pretty old, so old it predates most package manager support for Swift, so the best solution was to manually include source files for dependencies in your projects (people are still doing this.) However, it means it was harder to keep the local copy up-to-date. Every time I would try and update the local copy, I would lose the changes needed to support Objective-C. 

The main reason for moving the files out of the repo was to keep track of the manually changes made to Starscream and to make it easier to keep it up-to-date with the upstream. The changes made are very minor; just some things so that Objective-C doesn't complain.

**Comment by hashier** [comment]
Any recommendations how to set up cocoapods now? I used Starscream in cocoapods, now with the updated SocketIO what's your suggestion? Remove Starscream from the Podfile and just use the one that comes bundled with SocketIO?
Still it feels a bit clunky not to just have a dependency in the cocapod spec file to Starscream (but I get it, if you need changes on Starscream. I just hope I don't end up at some point that Starscream has features I need that you don't have in your copy of Starscream and I can't use Starscream because of name clashes.)

**Comment by nuclearace** [comment]
Well, I could do that if I wanted to drop Objective-C support (which has crossed my mind a few times.) The only other reason to have a fork is to test new Swift version that break syntax (which in early Swift was every minor release.)

You could use the custom fork if you want. It's generally up-to-date.

**Comment by hashier** [comment]
Thanks for all this insight!
