### ISSUE TITLE
WebSocket connection life cycle

### ISSUE THREAD

**Issue by ilandbt** [socketio/socket.io-client-swift#763]
I'm trying to understand the WebSocket's Connection life cycle.

when disconnecting the internet connection i get a `reconnect` event.
Why am i not getting a `disconnected` event? 

Is the any documentation for the connection life cycle?

Thanks

---------------

Log example:

```
//open app - wifi on
<DESCRIPTION> Socket-Manager: CONNECT
<DESCRIPTION> Socket-Manager: AUTHENTICATED
<DESCRIPTION> Socket-Manager: AUTHENTICATED
//turn wifi off
<DESCRIPTION> Socket-Manager: RECONNECT
//turn wifi on
<DESCRIPTION> Socket-Manager: CONNECT
<DESCRIPTION> Socket-Manager: AUTHENTICATED
<DESCRIPTION> Socket-Manager: AUTHENTICATED
```

**Comment by nuclearace** [comment]
There's no specific documentation for the life cycle of the WebSocket specifically, since it gets recreated for each connection.

The client behaves roughly like this:
NotConnected->Connecting->Connected->\<Working\>->\<Engine reports disconnect\>

From there a few things can happen.
If `disconnect` was called or the client isn't set to automatically reconnect: Status is disconnected and a `disconnect` event is emitted.
otherwise: `reconnect` is emitted and client attempts to reconnect, emitting `reconnectAttempt` events.
