### ISSUE TITLE
Handler received in SocketIOClient , but not in SocketIOManager iOS Swift

### ISSUE THREAD

**Issue by Harryiosdev** [socketio/socket.io-client-swift#777]
HI, 
I am working on SocketiOS Swift  and it works fine  before three days.
Suddenly the handler is not receiving in SocketIOManager class

When Soccer broadcast message from  server then the handler from SocketIOClient receives  but the handler from Socket.IOManager  is not working, 

Plz suggest me some solution , 

I am using this code to create socket from iOS side.

let socket = SocketIOClient(socketURL: URL(string: "http://52.37.102.214:2017")!, config: [.log(true), .compress])

and my handler in socketIOManager class is 

socket.once("get message") { ( dataArray, ack) -> Void in
            print(dataArray)
            print(ack)
            completionHandler( dataArray[0] as? [String: AnyObject])
        }
Should i need to make any Change in code , Please let me know

Thanks
Harry

**Comment by nuclearace** [comment]
The .once method will add a single use handle, after it's called once it won't be called again. Use .on if you want a handler than can be used multiple times.

**Comment by Harryiosdev** [comment]
Thanks for your reply

Let me try with that , and I will let you know.

Thanks Again buddy

**Comment by Harryiosdev** [comment]
Sorry to say 

/but after placing socket.Once with socket.on, its not working


This is happening , 
on socketIOClient side
and printing in my console.
 _LOG SocketIOClient: Handling event: get message with data:_ 

where "get message"  is my handler name
but the handler  on SocketIOManager not invoked.


Here is the handler code form SocketIOManager class is 

socket.removeAllHandlers()
        socket.on("get message") { ( dataArray, ack) -> Void in
            print(dataArray)
            print(ack)
            completionHandler( dataArray[0] as? [String: AnyObject])
        }
Please check it and  let me know
Thanks

**Comment by nuclearace** [comment]
What do you mean "handler on SocketIOManager not invoked"?

The line `LOG SocketIOClient: Handling event: get message with data:` means the client is about to call any event handlers that match that event name. If no handlers match that event name, it won't call any. 

It's completely up to you to make sure you're using your API correctly.

However some best practices IMO:
- Don't use dynamic events that require keeping track of different event handlers. It's complicated and error prone. Instead use an API with a predefined set of events and use the payloads to do any dynamic dispatching.
- If you absolutely must do some sort of dynamic events. Use `.once` so that you don't have to worry about removing handlers yourself.

In addition, it's crucial that you understand Swift's ARC. A lot of times when people say their events aren't being called, what's actually happening is their client is being released because they declared it as a local variable.

**Comment by Harryiosdev** [comment]
Alright, i understand that according to you its not calling may be the handler not matching.

but can you please tell me why its working from sender side and not on other users side in case of broadcasting ?

Whenever send message its invoked correctly, but when otherUser send message to sender back   its not working thats  what happening my side.


Please guide me.

**Comment by nuclearace** [comment]
I can't really be of anymore help since I don't what your API is like. But it sounds like the problem is most likely in the server logic if you think your client is being configured for the correct events. My knowledge of socket.io server is limited, so I won't be able to help much there.

**Comment by Harryiosdev** [comment]
Hi, nuclearace
Thanks for your guidence, Your suggestions really helped . 
You are a genius.
Thanks again.
