### ISSUE TITLE
Reconnecting problems with release version

### ISSUE THREAD

**Issue by tolgaytoklar** [socketio/socket.io-client-swift#969]
Hi

I am using this library for chat application. If user sends my app to background then comes back socket is not connecting. But this is happening only release (downloaded from app store) version. I am trying to debug this problem and connecting my phone to xcode and sending my app to background then when i came back it is connecting without any problem. What can be cause to this problem? Do you have an idea?

Version: V9.0.1

**Comment by nuclearace** [comment]
@tolgaytoklar Generally it's been my recommendation to turn off manual reconnects when the application goes into the background and re-establish the socket once the app comes back. Background execution has always caused problem with this library. (Since it's written to work on multiple platforms it doesn't do any special casing for iOS)
